packages:
    - name      : boost
      vcs       : git
      url       : https://github.com/boostorg/boost.git
      cmd       : conda build recipes/boost
      conda     : True
      recipe    : recipes/boost
      hierarchy : minor
      #directory : git_cache

run:
    - python test_function.py
