packages:
    - name      : scikit-image
      vcs       : conda
      cmd       : conda install -y
      supply    : minor
      channels  :
        - conda-forge
      hierarchy : patch
      directory : .vclimb

    - name      : scikit-learn
      vcs       : conda
      cmd       : conda install -y
      supply    : minor
      channels  :
        - conda-forge
      hierarchy : patch

    - name      : scipy
      vcs       : conda
      cmd       : conda install -y
      channels  :
        - conda-forge
      hierarchy : patch
      supply    : minor

    - name      : numpy
      vcs       : conda
      cmd       : conda install -y
      channels  :
        - conda-forge
      hierarchy : patch
      supply    : minor

run:
    - python estimate_hog.py

