{% set version = "1.3.3" %}

package:
  name: versionclimber
  version: {{version}}

source:
  path: ..

build:
  noarch: python
  number: 0
  entry_points:
    - vclimb = versionclimber.vclimb:main

  script: {{PYTHON}} setup.py install

requirements:
  host:
    - python {{PY_VER}}
    - setuptools

  run:
    - python
    - path
    - gitpython
    - pyyaml
    - six
    - requests
    - pyzmq

test:
  requires:
    - pytest
  imports:
    - versionclimber
    - versionclimber.utils
    - versionclimber.liquid
    - versionclimber.liquidparser

  source_files:
    - test/
    - test/config.yaml

  commands:
    - vclimb --help
    - cd test
    - pytest -v 

about:
  home: 'https://github.com/VersionClimber/VersionClimber'
  license: 'Cecill-C'
  summary: 'Version Climber: System and Algorithms for Package evolution in Data Science.'

extra:
  recipe-maintainers:
    - pradal
