packages:
    - name      : VersionClimber_tuto01
      vcs       : git
      url       : https://github.com/revesansparole/VersionClimber_tuto01.git
      cmd       : pip install --no-index --no-deps -U
      version   : v3.0
      hierarchy : major
      directory : git_cache

run:
    - python test_function.py

