packages:
    - name      : VersionClimber_test01
      vcs       : git
      url       : https://github.com/revesansparole/VersionClimber_test1.git
      cmd       : pip install --no-index --no-deps -U
      hierarchy : major
      #directory : git_cache

run:
    - python test_function.py
