pre: conda install -y -c conda-forge numpy scipy
packages:
    - name      : scikit-image
      vcs       : conda
      cmd       : conda install -y
      channels  :
        - conda-forge
      hierarchy : patch
      directory : .vclimb

    - name      : scikit-learn
      vcs       : conda
      cmd       : conda install -y
      channels  :
        - conda-forge
      hierarchy : patch

run:
    - python estimate_hog.py
post: conda env export > environment.yml
